# Generated by Django 4.0.4 on 2022-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_user_products_description_products_pro_img_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(default='0', max_length=100),
        ),
    ]
